Also stop the HTTP parser in addition to resetting it.
The behavior was depending on an exception raised later after resetting the parser
and then this resulting in parser not calling any further callback.
With http_parser.rb >= 0.6.1 this is no longer true.

Stopping the parser at this point seems correct as it also stops firing
additional callbacks from being called.

Fixes failure in test suite:
```
Failure/Error: if !client.continue?
     NoMethodError:
       undefined method `continue?' for nil:NilClass
```
From `EventMachine::HttpRequest should close connection on invalid HTTP response'.